In [1]:
import numpy as np

$$R^{-1} \times R = I$$

In [2]:
R = np.array([[2, 1],
			  [1, 1]])

R_inv = np.linalg.inv(R)

I = np.dot(R_inv, R)

print(f"Matrix:\n{R}\n\nInverse Matrix:\n{R_inv}\n\nIdentity Matrix:\n{I}")

Matrix:
[[2 1]
 [1 1]]

Inverse Matrix:
[[ 1. -1.]
 [-1.  2.]]

Identity Matrix:
[[1. 0.]
 [0. 1.]]


$$([A] \cdot [B])^{-1} = [B]^{-1} \cdot [A]^{-1}$$


In [3]:
A = np.array([[1, 1],
			  [0, 1]])

B = np.array([[1, 0],
			  [1, 1]])

A_inv = np.linalg.inv(A)
B_inv = np.linalg.inv(B)

AB = np.dot(A, B)

print(f"{np.linalg.inv(AB)}\n\n")
print(f"{np.dot(B_inv, A_inv)}\n\n")

[[ 1. -1.]
 [-1.  2.]]


[[ 1. -1.]
 [-1.  2.]]




### System of equations (2x2) - Normal 

$$[R] \cdot [a] = [A]$$

$$[R]^{-1} \cdot [R] \cdot [a] = [R]^{-1} \cdot [A]$$

$$I \cdot [a] = [R]^{-1} \cdot [A]$$

$$[a] = [R]^{-1} \cdot [A]$$


In [4]:
R = np.array([[2, 1],
			  [1, 1]])

A = np.array([[4],
			  [3]])

R_inv = np.linalg.inv(R)

a = np.dot(R_inv, A)

print(a)



[[1.]
 [2.]]


### System of equations (4x3) - Abnormal 


$$[R] \cdot [a] = [A]$$

$$[R]^{-1} = Impossible$$

In [ ]:
R = np.array([[1, 2, 1],
			  [2, 3, 1],
			  [4, 1, 2],
			  [1, 5, 2]]) # Not squared

A = np.array([[4],
			  [6],
			  [7],
			  [8]])

R_inv = np.linalg.inv(R) # LinAlgError: Last 2 dimensions of the array must be square

$$maybe...$$
$$[a] = \frac{1}{[R]} \cdot [A] ??$$

$$Pseudo-inverse$$
$$-----------------$$
$$[R] \cdot [a] = [A]$$
$$-----------------$$
$$[I] \cdot [R] \cdot [a] = [I] \cdot [A]$$
$$[R] \cdot [a] = [I] \cdot [A]$$
$$[R] \cdot [a] = [R^{t}]^{-1} \cdot [R^{t}] \cdot [A]$$
$$[R]^{-1} \cdot [R] \cdot [a] = [R]^{-1} \cdot [R^{t}]^{-1} \cdot [R^{t}] \cdot [A]$$
$$[a] = [R]^{-1} \cdot [R^{t}]^{-1} \cdot [R^{t}] \cdot [A]$$
$$-----------------$$
$$([A] \cdot [B])^{-1} = [B]^{-1} \cdot [A]^{-1}$$
$$([R^{t}] \cdot [R])^{-1} = [R]^{-1} \cdot [R^{t}]^{-1}$$
$$-----------------$$
$$[a] = ([R^{t}] \cdot [R])^{-1} \cdot [R^{t}] \cdot [A]$$
$$[a] = ([R^{t}] \cdot [R])^{-1} \cdot [R^{t}] \cdot [A]$$
$$[a] = \frac{1}{[R]} \cdot [A]$$
$$-----------------$$
$$\frac{1}{[R]} = ([R^{t}] \cdot [R])^{-1} \cdot [R^{t}]$$
$$-----------------$$



In [9]:
R = np.array([[1, 2, 1],
			  [2, 3, 1],
			  [4, 1, 2],
			  [1, 5, 2]])

A = np.array([[4],
			  [6],
			  [7],
			  [8]])

R_pseudo_inv = np.dot(np.linalg.inv(np.dot(R.T, R)), R.T)

a = np.dot(R_pseudo_inv, A)

print(a)

[[1.]
 [1.]
 [1.]]
